### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by ClemMakesApps** [dracula/sublime#1]
It would be nice to have a markdown theme. 
The default ones that come with [MarkdownEditing](https://github.com/SublimeText-Markdown/MarkdownEditing#markdownediting) aren't as 😱

> Previously requested at https://github.com/zenorocha/dracula-theme/issues/178

**Comment by ClemMakesApps** [comment]
@nesl247 if I submitted a PR for this, would you be willing to accept it?

**Comment by nesl247** [comment]
@ClemMakesApps Definitely.

**Comment by zenorocha** [comment]
Fixed on https://github.com/dracula/sublime/commit/dc87891be8e292f0fa62aaff809d146a38acb93f!

Thanks!
