### ISSUE TITLE
Sublime Text 3.0 is out

### ISSUE THREAD

**Issue by iatsiuk** [dracula/sublime#12]
Hi,

any updates for Sublime Text 3?

**Comment by Jadex1** [comment]
I second this.

**Comment by zenorocha** [comment]
Can you point it out what is not working?

**Comment by zenorocha** [comment]
By the way, I'm looking for new maintainers to this theme. Are you interested in taking it over @iatsiuk @Jadex1 @lee-reinhardt?

**Comment by Jadex1** [comment]
@zenorocha I just started using sublime. I don't even know how to fix what's broken with it. Someone from the sublime forum said sublime 3 changed the way the color api works. I've been using Atom, but wanted something that didn't drain my ram. I really like the dracula theme, and it not working is the only reason I'm not fully using sublime text 3 yet. https://forum.sublimetext.com/t/dracula-syntax-highlighting/31637/4

**Comment by lee-reinhardt** [comment]
@zenorocha I would potentially be interested. I still use this theme every day for several languages, like JS, PHP, Python, Elixir, etc. I figured out enough to hack in a fix and submit a PR, so if that's the type of help you're looking for, I'm game.

**Comment by zenorocha** [comment]
that's exactly the kind of help we need @lee-reinhardt!

**Comment by lee-reinhardt** [comment]
I just released version `1.4.0`, which addresses lots of various things I found and fixed across several languages. If there's anything else people want looked at, please open a new issue with a relevant screenshot/example.
