### ISSUE TITLE
PHP syntax issue: the closing tag is not the same.

### ISSUE THREAD

**Issue by yonishin** [dracula/sublime#13]
<img width="780" alt="screen shot 2017-10-20 at 18 54 13" src="https://user-images.githubusercontent.com/502421/31830379-b12c56a0-b5c8-11e7-8958-91c2c84c681b.png">

Sublime Text 3, Bulid 3143
MacOS Version 10.13

**Comment by lee-reinhardt** [comment]
Thanks for the report. I should have a chance to fix this in the next day or so.
