### ISSUE TITLE
Is this the TextMate theme and not the SublimeText one? EOM

### ISSUE THREAD

**Issue by johnwyles** [dracula/sublime#17]

**Comment by diegotoral** [comment]
SublimeText 3 (at least) supports this file format as per [docs](https://www.sublimetext.com/docs/3/color_schemes_tmtheme.html).

**Comment by johnwyles** [comment]
@diegotoral should this be closed?

**Comment by diegotoral** [comment]
Yeah, I think so.

**Comment by johnwyles** [comment]
Closing per previous comments ^
