### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by nesl247** [dracula/sublime#2]
Hey everyone,

We're looking for a maintainer for Sublime. Dracula theme has grown significantly and it's too much for one person. If you are interested in becoming the maintainer, please reply here.

We're not going to let issues and pull requests get behind though just because we don't have a dedicated maintainer, so fear not.

Thanks.
- Dracula Theme Team

**Comment by charlietran** [comment]
I'd like to help! Let me know what I can do.

**Comment by zenorocha** [comment]
Hey @charlietran, are you still interested in maintaining this theme? Looks like the only pull request opened is still yours.
