### ISSUE TITLE
Error loading color scheme when .md file is opened or closed.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [dracula/sublime#24]
When I open or close .md files they are not displayed with Dracula theme and this error pops up:
![sublime_text_54BsNpRc2p](https://user-images.githubusercontent.com/21691213/90248389-47f99180-de41-11ea-89ca-ee9ce28d8d5b.png)

**Comment by zenorocha** [comment]
This error is not related to Dracula. As you can see from the error message, it's related to Dark Material.
