### ISSUE TITLE
Theme not compatible with Sublime Text 4

### ISSUE THREAD

**Issue by stuarthallows** [dracula/sublime#25]
This theme does not load when installed into Sublime Text 4.

**Comment by zenorocha** [comment]
It seems to be working fine over here.

<img width="1186" alt="Screen Shot 2021-05-30 at 3 21 56 PM" src="https://user-images.githubusercontent.com/398893/120121884-cb7b3980-c15a-11eb-88a7-e28c30f5b7c2.png">

**Comment by stuarthallows** [comment]
Indeed. In fact it worked for me on another installation.
