### ISSUE TITLE
How to change Sidebar color

### ISSUE THREAD

**Issue by andreepratama27** [dracula/sublime#4]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

In material-theme or other, I always set "theme" in the user configuration with this (example i'm using material theme") : 
"theme": Material-Theme.sublime-theme

I do the same with this dracula theme, with 'Dracula' in the theme. But i didn't get the result. This is the result when I set theme to the Dracula or Dracula (SL) : 

![screenshot from 2016-10-25 14-36-37](https://cloud.githubusercontent.com/assets/7699523/19676814/7cdd38f2-9ac0-11e6-9588-ba2baf185b69.png)

**Comment by zenorocha** [comment]
Hello @andreepratama27, sorry for taking so long to reply. 

This is because Dracula is a color scheme, not a UI theme like Material.
