### ISSUE TITLE
Sidebar color doesn't seem right

### ISSUE THREAD

**Issue by matthew-groth** [dracula/sublime#5]
![image](https://cloud.githubusercontent.com/assets/12831489/23774682/e2382db4-04f2-11e7-98c9-56aab620d557.png)

**Comment by matthew-groth** [comment]
Of course this could be intentional for the sake of contrast, I just thought maybe the sidebar could also be dark.

**Comment by zenorocha** [comment]
Hey @matthew-groth, thanks for reporting. This theme only offers a different color scheme not a full editor change. That's why the sidebar still the same. But feel free to contribute, pull requests are welcome :D
